# Generated by Django 6.0.6 on 2026-07-09 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='last_credited',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 9, 1, 11, 28, 95154, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
