# Generated by Django 6.0.6 on 2026-07-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transactions_last_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='last_credited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
